from reportlab.pdfgen import canvas
import os

output_folder = "/home/jetson/xray_results"
os.makedirs(output_folder, exist_ok=True)

def save_report(image_name, label, confidence, recommendation):
    report_path = os.path.join(output_folder, f"{image_name}_report.pdf")
    c = canvas.Canvas(report_path)
    
    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, 770, "AI X-Ray Fracture Detection Report")
    c.line(100, 765, 480, 765)
    
    # Content
    c.setFont("Helvetica", 12)
    c.drawString(100, 730, f"Image Name: {image_name}")
    c.drawString(100, 705, f"Fracture Status: {label}")
    c.drawString(100, 680, f"Confidence: {confidence*100:.2f}%")
    c.drawString(100, 655, f"Recommendation:")
    
    # Wrap long text
    text_obj = c.beginText(120, 630)
    text_obj.textLines(recommendation)
    c.drawText(text_obj)

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(100, 100, "Generated by Jetson Orin Nano | AI Medical Helper")
    
    c.save()
    print(f"📄 Report saved: {report_path}")